# -*- coding: utf-8 -*-
"""03_Donguler_Loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOB_i1JxIyuBdhGXdrHR-CHreT3nHl-g
"""

#0'dan 10'a Sayma
for i in range(0, 11):
    print(i)

#İlk 5 Sayının Toplamı
toplam = 0
for i in range(6):
    toplam += i
print(toplam)

#Çift Sayıların Toplamı
toplam = 0
for i in range(0, 11, 2):
    toplam += i
print(toplam)

#3'e Bölünen Sayılar
for i in range(1, 51):
    if i % 3 == 0:
        print(i)

#Şifre Kontrolü - Doğru Olana Kadarsifre = "Ayse123"
a = input("Lütfen şifrenizi giriniz: ")
while a != sifre:
    a = input("Şifre yanlış.Tekrar giriniz: ")
print("Şifre doğru.")

#Faktöriyel Hesaplama
faktoriyel = 1
sayi = int(input("Faktöriyelini hesaplamak istediğiniz sayıyı girin: "))
while sayi > 1:
    faktoriyel *= sayi
    sayi -= 1
print(f"Girdiğiniz sayının faktöriyeli {faktoriyel}' dir.")