# -*- coding: utf-8 -*-
"""04_Listeler_ve_Donguler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKLfTA8ROE0rm48wBbOWyWXF-tBXtwKM
"""

#Paket Ağırlık Filtreleme
paket_agirliklari = [1.2, 5.5, 0.8, 12.4, 3.1, 8.0]
for agirlik in paket_agirliklari:
    if agirlik >= 5:
        print(f"Ağır paket: {agirlik} kg")

#Sepet Tutarı Filtreleme
yeni_sepetler = [2500, 150, 850, 4200, 950]
for sepet in yeni_sepetler:
    if sepet > 1500:
        print(f"Büyük satış: {sepet} ")

#Listedeki Çift Sayıları Ayıklama
liste = [12, 4, 9, 92, 27, 34, 60, 8, 28, 19, 71]
yeni_liste = []
for sayi in liste:
    if sayi % 2 == 0:
        yeni_liste.append(sayi)
print(yeni_liste)

#Hazır Metotla En Büyük/En Küçük
sayilar = [12, 45, 2, 89, 34, 6]
print(f"En büyük sayı {max(sayilar)} en küçük sayı {min(sayilar)} dır.")

#En Büyük/En Küçük
sayilar = [12, 45, 2, 89, 34, 6]
en_büyük = sayilar[0]
en_kücük = sayilar[0]
for sayi in sayilar:
    if sayi > en_büyük:
        en_büyük = sayi
    elif sayi < en_kücük:
        en_kücük = sayi
print(f"En büyük sayı {en_büyük}, en küçük sayı {en_kücük} dir.")