# -*- coding: utf-8 -*-
"""temel_hesaplamalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGhFxcaPQlqNzr4XydDi_7YFeK3S2w1m
"""

#Karenin Alanı ve Çevresi
a = float(input('Karenin bir kenar uzunluğunu giriniz: '))
alan = a * a
cevre =u 4 * a
print(f'Karenin alanı {alan} çevresi {cevre} dir')

#Doğum Yılı ile Yaş Hesaplama
dogum_yili = input("Doğum yılınızı giriniz: ")
yas = 2026 - int(dogum_yili)
print(f"Yaşınız {yas} dır.")

#Üç Sayının Ortalaması
sayi1 = float(input("Birinci sayıyı giriniz: "))
sayi2 = float(input("İkinci sayıyı giriniz: "))
sayi3 = float(input("Üçüncü sayıyı giriniz: "))
ort = (sayi1 + sayi2 + sayi3) / 3
print(f"Girdiğiniz sayıların ortalaması {ort} dur.")

#Kare, Küp ve Karekök Hesaplama
import math
a = float(input("Lütfen bir sayı giriniz: "))
kare = a**2
kup = a**3
karekok = math.sqrt(a)
print(f"Girdiğiniz sayının karesi {kare} küpü {kup} ve karekökü {karekok} dür.")